### ISSUE TITLE
Añadir hostname en los mensajes

### ISSUE THREAD

**Issue by gmag11** [atareao/den#1]
Hola. ¿Cómo podría añadir el hostname en los mensajes?

He añadido la variable de entorno HOST_HOSTNAME. Éste es mi docker-compose:

```
version: '3'
services:
    den:
        container_name: den
        restart: unless-stopped
        image: atareao/den
        environment:
          - HOST_HOSTNAME=mi_hostname
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./config.yml:/app/config.yml
```

En la configuración he probado a añadir `${HOST_HOSTNAME}` y `${{HOST_HOSTNAME}}` a los mensajes pero ninguna de las opciones funciona.
