### ISSUE TITLE
Panic en el envío de mensaje network destroy

### ISSUE THREAD

**Issue by gmag11** [atareao/den#2]
Hola, cuando se producen mensajes de destrucción de redes de contenedores aparece esto en el log:

```
den  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Event { typ: "network", action: "destroy", actor: Actor { id: "f3047781314269121c8674eee8c589f8163235bd356a9fc8aafa21bbb47bfb5f", attributes: {"type": "bridge", "name": "portainer_default"} }, status: None, id: None, from: None, time: 2022-11-17T12:55:20Z, time_nano: 2022-11-17T12:55:20.694089444Z })', src/main.rs:69:36
```

La configuración que tengo en la sección network es:

```
  - name: network
    monitorize: true
    # create, connect, destroy, disconnect, remove
    events:
      - name: create
        message: Created network **{{ network }}**
      - name: destroy
        message: Destroyed network **{{ network }}**
      - name: remove
        message: 💥 Removed network **{{ network }}**
```
